/*
 * This file is generated by jOOQ.
 */
package com.vancefm.ticketstack.models;


import com.vancefm.ticketstack.models.tables.Contact;
import com.vancefm.ticketstack.models.tables.RequestCategory;
import com.vancefm.ticketstack.models.tables.Ticket;
import com.vancefm.ticketstack.models.tables.TicketStatus;
import com.vancefm.ticketstack.models.tables.records.ContactRecord;
import com.vancefm.ticketstack.models.tables.records.RequestCategoryRecord;
import com.vancefm.ticketstack.models.tables.records.TicketRecord;
import com.vancefm.ticketstack.models.tables.records.TicketStatusRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * ticketstack.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ContactRecord> KEY_CONTACT_EMAIL_ADDRESS = Internal.createUniqueKey(Contact.CONTACT, DSL.name("KEY_contact_email_address"), new TableField[] { Contact.CONTACT.EMAIL_ADDRESS }, true);
    public static final UniqueKey<ContactRecord> KEY_CONTACT_PRIMARY = Internal.createUniqueKey(Contact.CONTACT, DSL.name("KEY_contact_PRIMARY"), new TableField[] { Contact.CONTACT.ID }, true);
    public static final UniqueKey<RequestCategoryRecord> KEY_REQUEST_CATEGORY_CATEGORY = Internal.createUniqueKey(RequestCategory.REQUEST_CATEGORY, DSL.name("KEY_request_category_category"), new TableField[] { RequestCategory.REQUEST_CATEGORY.CATEGORY }, true);
    public static final UniqueKey<RequestCategoryRecord> KEY_REQUEST_CATEGORY_PRIMARY = Internal.createUniqueKey(RequestCategory.REQUEST_CATEGORY, DSL.name("KEY_request_category_PRIMARY"), new TableField[] { RequestCategory.REQUEST_CATEGORY.ID }, true);
    public static final UniqueKey<TicketRecord> KEY_TICKET_PRIMARY = Internal.createUniqueKey(Ticket.TICKET, DSL.name("KEY_ticket_PRIMARY"), new TableField[] { Ticket.TICKET.ID }, true);
    public static final UniqueKey<TicketStatusRecord> KEY_TICKET_STATUS_PRIMARY = Internal.createUniqueKey(TicketStatus.TICKET_STATUS, DSL.name("KEY_ticket_status_PRIMARY"), new TableField[] { TicketStatus.TICKET_STATUS.ID }, true);
    public static final UniqueKey<TicketStatusRecord> KEY_TICKET_STATUS_STATUS_NAME = Internal.createUniqueKey(TicketStatus.TICKET_STATUS, DSL.name("KEY_ticket_status_status_name"), new TableField[] { TicketStatus.TICKET_STATUS.STATUS_NAME }, true);
}
