/*
 * This file is generated by jOOQ.
 */
package com.vancefm.ticketstack.models;


import com.vancefm.ticketstack.models.tables.Contact;
import com.vancefm.ticketstack.models.tables.RequestCategory;
import com.vancefm.ticketstack.models.tables.Ticket;
import com.vancefm.ticketstack.models.tables.TicketStatus;


/**
 * Convenience access to all tables in ticketstack.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ticketstack.contact</code>.
     */
    public static final Contact CONTACT = Contact.CONTACT;

    /**
     * The table <code>ticketstack.request_category</code>.
     */
    public static final RequestCategory REQUEST_CATEGORY = RequestCategory.REQUEST_CATEGORY;

    /**
     * The table <code>ticketstack.ticket</code>.
     */
    public static final Ticket TICKET = Ticket.TICKET;

    /**
     * The table <code>ticketstack.ticket_status</code>.
     */
    public static final TicketStatus TICKET_STATUS = TicketStatus.TICKET_STATUS;
}
