/*
 * This file is generated by jOOQ.
 */
package com.vancefm.ticketstack.models;


import com.vancefm.ticketstack.models.tables.Contact;
import com.vancefm.ticketstack.models.tables.RequestCategory;
import com.vancefm.ticketstack.models.tables.Ticket;
import com.vancefm.ticketstack.models.tables.TicketStatus;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ticketstack extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ticketstack</code>
     */
    public static final Ticketstack TICKETSTACK = new Ticketstack();

    /**
     * The table <code>ticketstack.contact</code>.
     */
    public final Contact CONTACT = Contact.CONTACT;

    /**
     * The table <code>ticketstack.request_category</code>.
     */
    public final RequestCategory REQUEST_CATEGORY = RequestCategory.REQUEST_CATEGORY;

    /**
     * The table <code>ticketstack.ticket</code>.
     */
    public final Ticket TICKET = Ticket.TICKET;

    /**
     * The table <code>ticketstack.ticket_status</code>.
     */
    public final TicketStatus TICKET_STATUS = TicketStatus.TICKET_STATUS;

    /**
     * No further instances allowed
     */
    private Ticketstack() {
        super("ticketstack", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Contact.CONTACT,
            RequestCategory.REQUEST_CATEGORY,
            Ticket.TICKET,
            TicketStatus.TICKET_STATUS);
    }
}
