/*
 * This file is generated by jOOQ.
 */
package com.vancefm.ticketstack.models.tables;


import com.vancefm.ticketstack.models.Keys;
import com.vancefm.ticketstack.models.Ticketstack;
import com.vancefm.ticketstack.models.tables.records.RequestCategoryRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RequestCategory extends TableImpl<RequestCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ticketstack.request_category</code>
     */
    public static final RequestCategory REQUEST_CATEGORY = new RequestCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RequestCategoryRecord> getRecordType() {
        return RequestCategoryRecord.class;
    }

    /**
     * The column <code>ticketstack.request_category.id</code>.
     */
    public final TableField<RequestCategoryRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>ticketstack.request_category.category</code>.
     */
    public final TableField<RequestCategoryRecord, String> CATEGORY = createField(DSL.name("category"), SQLDataType.VARCHAR(25).nullable(false), this, "");

    private RequestCategory(Name alias, Table<RequestCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private RequestCategory(Name alias, Table<RequestCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>ticketstack.request_category</code> table reference
     */
    public RequestCategory(String alias) {
        this(DSL.name(alias), REQUEST_CATEGORY);
    }

    /**
     * Create an aliased <code>ticketstack.request_category</code> table reference
     */
    public RequestCategory(Name alias) {
        this(alias, REQUEST_CATEGORY);
    }

    /**
     * Create a <code>ticketstack.request_category</code> table reference
     */
    public RequestCategory() {
        this(DSL.name("request_category"), null);
    }

    public <O extends Record> RequestCategory(Table<O> child, ForeignKey<O, RequestCategoryRecord> key) {
        super(child, key, REQUEST_CATEGORY);
    }

    @Override
    public Schema getSchema() {
        return Ticketstack.TICKETSTACK;
    }

    @Override
    public Identity<RequestCategoryRecord, Integer> getIdentity() {
        return (Identity<RequestCategoryRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<RequestCategoryRecord> getPrimaryKey() {
        return Keys.KEY_REQUEST_CATEGORY_PRIMARY;
    }

    @Override
    public List<UniqueKey<RequestCategoryRecord>> getKeys() {
        return Arrays.<UniqueKey<RequestCategoryRecord>>asList(Keys.KEY_REQUEST_CATEGORY_PRIMARY, Keys.KEY_REQUEST_CATEGORY_CATEGORY);
    }

    @Override
    public RequestCategory as(String alias) {
        return new RequestCategory(DSL.name(alias), this);
    }

    @Override
    public RequestCategory as(Name alias) {
        return new RequestCategory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RequestCategory rename(String name) {
        return new RequestCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RequestCategory rename(Name name) {
        return new RequestCategory(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
