/*
 * This file is generated by jOOQ.
 */
package com.vancefm.ticketstack.models.tables;


import com.vancefm.ticketstack.models.Keys;
import com.vancefm.ticketstack.models.Ticketstack;
import com.vancefm.ticketstack.models.tables.records.TicketRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ticket extends TableImpl<TicketRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ticketstack.ticket</code>
     */
    public static final Ticket TICKET = new Ticket();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TicketRecord> getRecordType() {
        return TicketRecord.class;
    }

    /**
     * The column <code>ticketstack.ticket.id</code>.
     */
    public final TableField<TicketRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>ticketstack.ticket.subject</code>.
     */
    public final TableField<TicketRecord, String> SUBJECT = createField(DSL.name("subject"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>ticketstack.ticket.contact_id</code>.
     */
    public final TableField<TicketRecord, Integer> CONTACT_ID = createField(DSL.name("contact_id"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ticketstack.ticket.request_category_id</code>.
     */
    public final TableField<TicketRecord, Integer> REQUEST_CATEGORY_ID = createField(DSL.name("request_category_id"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ticketstack.ticket.description</code>.
     */
    public final TableField<TicketRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(2000).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ticketstack.ticket.status_id</code>.
     */
    public final TableField<TicketRecord, Integer> STATUS_ID = createField(DSL.name("status_id"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ticketstack.ticket.created_time</code>.
     */
    public final TableField<TicketRecord, LocalDateTime> CREATED_TIME = createField(DSL.name("created_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("current_timestamp()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>ticketstack.ticket.updated_time</code>.
     */
    public final TableField<TicketRecord, LocalDateTime> UPDATED_TIME = createField(DSL.name("updated_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("current_timestamp()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>ticketstack.ticket.closed_time</code>.
     */
    public final TableField<TicketRecord, LocalDateTime> CLOSED_TIME = createField(DSL.name("closed_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "");

    private Ticket(Name alias, Table<TicketRecord> aliased) {
        this(alias, aliased, null);
    }

    private Ticket(Name alias, Table<TicketRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>ticketstack.ticket</code> table reference
     */
    public Ticket(String alias) {
        this(DSL.name(alias), TICKET);
    }

    /**
     * Create an aliased <code>ticketstack.ticket</code> table reference
     */
    public Ticket(Name alias) {
        this(alias, TICKET);
    }

    /**
     * Create a <code>ticketstack.ticket</code> table reference
     */
    public Ticket() {
        this(DSL.name("ticket"), null);
    }

    public <O extends Record> Ticket(Table<O> child, ForeignKey<O, TicketRecord> key) {
        super(child, key, TICKET);
    }

    @Override
    public Schema getSchema() {
        return Ticketstack.TICKETSTACK;
    }

    @Override
    public Identity<TicketRecord, Integer> getIdentity() {
        return (Identity<TicketRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TicketRecord> getPrimaryKey() {
        return Keys.KEY_TICKET_PRIMARY;
    }

    @Override
    public List<UniqueKey<TicketRecord>> getKeys() {
        return Arrays.<UniqueKey<TicketRecord>>asList(Keys.KEY_TICKET_PRIMARY);
    }

    @Override
    public Ticket as(String alias) {
        return new Ticket(DSL.name(alias), this);
    }

    @Override
    public Ticket as(Name alias) {
        return new Ticket(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ticket rename(String name) {
        return new Ticket(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ticket rename(Name name) {
        return new Ticket(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, Integer, Integer, String, Integer, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
