/*
 * This file is generated by jOOQ.
 */
package com.vancefm.ticketstack.models.tables;


import com.vancefm.ticketstack.models.Keys;
import com.vancefm.ticketstack.models.Ticketstack;
import com.vancefm.ticketstack.models.tables.records.TicketStatusRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TicketStatus extends TableImpl<TicketStatusRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ticketstack.ticket_status</code>
     */
    public static final TicketStatus TICKET_STATUS = new TicketStatus();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TicketStatusRecord> getRecordType() {
        return TicketStatusRecord.class;
    }

    /**
     * The column <code>ticketstack.ticket_status.id</code>.
     */
    public final TableField<TicketStatusRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>ticketstack.ticket_status.status_name</code>.
     */
    public final TableField<TicketStatusRecord, String> STATUS_NAME = createField(DSL.name("status_name"), SQLDataType.VARCHAR(25).nullable(false), this, "");

    private TicketStatus(Name alias, Table<TicketStatusRecord> aliased) {
        this(alias, aliased, null);
    }

    private TicketStatus(Name alias, Table<TicketStatusRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>ticketstack.ticket_status</code> table reference
     */
    public TicketStatus(String alias) {
        this(DSL.name(alias), TICKET_STATUS);
    }

    /**
     * Create an aliased <code>ticketstack.ticket_status</code> table reference
     */
    public TicketStatus(Name alias) {
        this(alias, TICKET_STATUS);
    }

    /**
     * Create a <code>ticketstack.ticket_status</code> table reference
     */
    public TicketStatus() {
        this(DSL.name("ticket_status"), null);
    }

    public <O extends Record> TicketStatus(Table<O> child, ForeignKey<O, TicketStatusRecord> key) {
        super(child, key, TICKET_STATUS);
    }

    @Override
    public Schema getSchema() {
        return Ticketstack.TICKETSTACK;
    }

    @Override
    public Identity<TicketStatusRecord, Integer> getIdentity() {
        return (Identity<TicketStatusRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TicketStatusRecord> getPrimaryKey() {
        return Keys.KEY_TICKET_STATUS_PRIMARY;
    }

    @Override
    public List<UniqueKey<TicketStatusRecord>> getKeys() {
        return Arrays.<UniqueKey<TicketStatusRecord>>asList(Keys.KEY_TICKET_STATUS_PRIMARY, Keys.KEY_TICKET_STATUS_STATUS_NAME);
    }

    @Override
    public TicketStatus as(String alias) {
        return new TicketStatus(DSL.name(alias), this);
    }

    @Override
    public TicketStatus as(Name alias) {
        return new TicketStatus(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TicketStatus rename(String name) {
        return new TicketStatus(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TicketStatus rename(Name name) {
        return new TicketStatus(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
