/*
 * This file is generated by jOOQ.
 */
package com.vancefm.ticketstack.models.tables.pojos;


import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contact implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  emailAddress;
    private String  firstName;
    private String  lastName;

    public Contact() {}

    public Contact(Contact value) {
        this.id = value.id;
        this.emailAddress = value.emailAddress;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
    }

    public Contact(
        Integer id,
        String  emailAddress,
        String  firstName,
        String  lastName
    ) {
        this.id = id;
        this.emailAddress = emailAddress;
        this.firstName = firstName;
        this.lastName = lastName;
    }

    /**
     * Getter for <code>ticketstack.contact.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>ticketstack.contact.id</code>.
     */
    public Contact setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>ticketstack.contact.email_address</code>.
     */
    @NotNull
    @Size(max = 320)
    public String getEmailAddress() {
        return this.emailAddress;
    }

    /**
     * Setter for <code>ticketstack.contact.email_address</code>.
     */
    public Contact setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
        return this;
    }

    /**
     * Getter for <code>ticketstack.contact.first_name</code>.
     */
    @Size(max = 100)
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>ticketstack.contact.first_name</code>.
     */
    public Contact setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Getter for <code>ticketstack.contact.last_name</code>.
     */
    @Size(max = 100)
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>ticketstack.contact.last_name</code>.
     */
    public Contact setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Contact other = (Contact) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (emailAddress == null) {
            if (other.emailAddress != null)
                return false;
        }
        else if (!emailAddress.equals(other.emailAddress))
            return false;
        if (firstName == null) {
            if (other.firstName != null)
                return false;
        }
        else if (!firstName.equals(other.firstName))
            return false;
        if (lastName == null) {
            if (other.lastName != null)
                return false;
        }
        else if (!lastName.equals(other.lastName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.emailAddress == null) ? 0 : this.emailAddress.hashCode());
        result = prime * result + ((this.firstName == null) ? 0 : this.firstName.hashCode());
        result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Contact (");

        sb.append(id);
        sb.append(", ").append(emailAddress);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);

        sb.append(")");
        return sb.toString();
    }
}
