/*
 * This file is generated by jOOQ.
 */
package com.vancefm.ticketstack.models.tables.pojos;


import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RequestCategory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  category;

    public RequestCategory() {}

    public RequestCategory(RequestCategory value) {
        this.id = value.id;
        this.category = value.category;
    }

    public RequestCategory(
        Integer id,
        String  category
    ) {
        this.id = id;
        this.category = category;
    }

    /**
     * Getter for <code>ticketstack.request_category.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>ticketstack.request_category.id</code>.
     */
    public RequestCategory setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>ticketstack.request_category.category</code>.
     */
    @NotNull
    @Size(max = 25)
    public String getCategory() {
        return this.category;
    }

    /**
     * Setter for <code>ticketstack.request_category.category</code>.
     */
    public RequestCategory setCategory(String category) {
        this.category = category;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RequestCategory other = (RequestCategory) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (category == null) {
            if (other.category != null)
                return false;
        }
        else if (!category.equals(other.category))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.category == null) ? 0 : this.category.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RequestCategory (");

        sb.append(id);
        sb.append(", ").append(category);

        sb.append(")");
        return sb.toString();
    }
}
