/*
 * This file is generated by jOOQ.
 */
package com.vancefm.ticketstack.models.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ticket implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        subject;
    private Integer       contactId;
    private Integer       requestCategoryId;
    private String        description;
    private Integer       statusId;
    private LocalDateTime createdTime;
    private LocalDateTime updatedTime;
    private LocalDateTime closedTime;

    public Ticket() {}

    public Ticket(Ticket value) {
        this.id = value.id;
        this.subject = value.subject;
        this.contactId = value.contactId;
        this.requestCategoryId = value.requestCategoryId;
        this.description = value.description;
        this.statusId = value.statusId;
        this.createdTime = value.createdTime;
        this.updatedTime = value.updatedTime;
        this.closedTime = value.closedTime;
    }

    public Ticket(
        Integer       id,
        String        subject,
        Integer       contactId,
        Integer       requestCategoryId,
        String        description,
        Integer       statusId,
        LocalDateTime createdTime,
        LocalDateTime updatedTime,
        LocalDateTime closedTime
    ) {
        this.id = id;
        this.subject = subject;
        this.contactId = contactId;
        this.requestCategoryId = requestCategoryId;
        this.description = description;
        this.statusId = statusId;
        this.createdTime = createdTime;
        this.updatedTime = updatedTime;
        this.closedTime = closedTime;
    }

    /**
     * Getter for <code>ticketstack.ticket.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>ticketstack.ticket.id</code>.
     */
    public Ticket setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket.subject</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getSubject() {
        return this.subject;
    }

    /**
     * Setter for <code>ticketstack.ticket.subject</code>.
     */
    public Ticket setSubject(String subject) {
        this.subject = subject;
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket.contact_id</code>.
     */
    public Integer getContactId() {
        return this.contactId;
    }

    /**
     * Setter for <code>ticketstack.ticket.contact_id</code>.
     */
    public Ticket setContactId(Integer contactId) {
        this.contactId = contactId;
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket.request_category_id</code>.
     */
    public Integer getRequestCategoryId() {
        return this.requestCategoryId;
    }

    /**
     * Setter for <code>ticketstack.ticket.request_category_id</code>.
     */
    public Ticket setRequestCategoryId(Integer requestCategoryId) {
        this.requestCategoryId = requestCategoryId;
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket.description</code>.
     */
    @Size(max = 2000)
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>ticketstack.ticket.description</code>.
     */
    public Ticket setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket.status_id</code>.
     */
    public Integer getStatusId() {
        return this.statusId;
    }

    /**
     * Setter for <code>ticketstack.ticket.status_id</code>.
     */
    public Ticket setStatusId(Integer statusId) {
        this.statusId = statusId;
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket.created_time</code>.
     */
    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }

    /**
     * Setter for <code>ticketstack.ticket.created_time</code>.
     */
    public Ticket setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket.updated_time</code>.
     */
    public LocalDateTime getUpdatedTime() {
        return this.updatedTime;
    }

    /**
     * Setter for <code>ticketstack.ticket.updated_time</code>.
     */
    public Ticket setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket.closed_time</code>.
     */
    public LocalDateTime getClosedTime() {
        return this.closedTime;
    }

    /**
     * Setter for <code>ticketstack.ticket.closed_time</code>.
     */
    public Ticket setClosedTime(LocalDateTime closedTime) {
        this.closedTime = closedTime;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Ticket other = (Ticket) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (subject == null) {
            if (other.subject != null)
                return false;
        }
        else if (!subject.equals(other.subject))
            return false;
        if (contactId == null) {
            if (other.contactId != null)
                return false;
        }
        else if (!contactId.equals(other.contactId))
            return false;
        if (requestCategoryId == null) {
            if (other.requestCategoryId != null)
                return false;
        }
        else if (!requestCategoryId.equals(other.requestCategoryId))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (statusId == null) {
            if (other.statusId != null)
                return false;
        }
        else if (!statusId.equals(other.statusId))
            return false;
        if (createdTime == null) {
            if (other.createdTime != null)
                return false;
        }
        else if (!createdTime.equals(other.createdTime))
            return false;
        if (updatedTime == null) {
            if (other.updatedTime != null)
                return false;
        }
        else if (!updatedTime.equals(other.updatedTime))
            return false;
        if (closedTime == null) {
            if (other.closedTime != null)
                return false;
        }
        else if (!closedTime.equals(other.closedTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.subject == null) ? 0 : this.subject.hashCode());
        result = prime * result + ((this.contactId == null) ? 0 : this.contactId.hashCode());
        result = prime * result + ((this.requestCategoryId == null) ? 0 : this.requestCategoryId.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.statusId == null) ? 0 : this.statusId.hashCode());
        result = prime * result + ((this.createdTime == null) ? 0 : this.createdTime.hashCode());
        result = prime * result + ((this.updatedTime == null) ? 0 : this.updatedTime.hashCode());
        result = prime * result + ((this.closedTime == null) ? 0 : this.closedTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Ticket (");

        sb.append(id);
        sb.append(", ").append(subject);
        sb.append(", ").append(contactId);
        sb.append(", ").append(requestCategoryId);
        sb.append(", ").append(description);
        sb.append(", ").append(statusId);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(updatedTime);
        sb.append(", ").append(closedTime);

        sb.append(")");
        return sb.toString();
    }
}
