/*
 * This file is generated by jOOQ.
 */
package com.vancefm.ticketstack.models.tables.pojos;


import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TicketStatus implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  statusName;

    public TicketStatus() {}

    public TicketStatus(TicketStatus value) {
        this.id = value.id;
        this.statusName = value.statusName;
    }

    public TicketStatus(
        Integer id,
        String  statusName
    ) {
        this.id = id;
        this.statusName = statusName;
    }

    /**
     * Getter for <code>ticketstack.ticket_status.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>ticketstack.ticket_status.id</code>.
     */
    public TicketStatus setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket_status.status_name</code>.
     */
    @NotNull
    @Size(max = 25)
    public String getStatusName() {
        return this.statusName;
    }

    /**
     * Setter for <code>ticketstack.ticket_status.status_name</code>.
     */
    public TicketStatus setStatusName(String statusName) {
        this.statusName = statusName;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TicketStatus other = (TicketStatus) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (statusName == null) {
            if (other.statusName != null)
                return false;
        }
        else if (!statusName.equals(other.statusName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.statusName == null) ? 0 : this.statusName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TicketStatus (");

        sb.append(id);
        sb.append(", ").append(statusName);

        sb.append(")");
        return sb.toString();
    }
}
