/*
 * This file is generated by jOOQ.
 */
package com.vancefm.ticketstack.models.tables.records;


import com.vancefm.ticketstack.models.tables.Contact;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContactRecord extends UpdatableRecordImpl<ContactRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ticketstack.contact.id</code>.
     */
    public ContactRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ticketstack.contact.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ticketstack.contact.email_address</code>.
     */
    public ContactRecord setEmailAddress(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ticketstack.contact.email_address</code>.
     */
    public String getEmailAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ticketstack.contact.first_name</code>.
     */
    public ContactRecord setFirstName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ticketstack.contact.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ticketstack.contact.last_name</code>.
     */
    public ContactRecord setLastName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ticketstack.contact.last_name</code>.
     */
    public String getLastName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Contact.CONTACT.ID;
    }

    @Override
    public Field<String> field2() {
        return Contact.CONTACT.EMAIL_ADDRESS;
    }

    @Override
    public Field<String> field3() {
        return Contact.CONTACT.FIRST_NAME;
    }

    @Override
    public Field<String> field4() {
        return Contact.CONTACT.LAST_NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getEmailAddress();
    }

    @Override
    public String component3() {
        return getFirstName();
    }

    @Override
    public String component4() {
        return getLastName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getEmailAddress();
    }

    @Override
    public String value3() {
        return getFirstName();
    }

    @Override
    public String value4() {
        return getLastName();
    }

    @Override
    public ContactRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ContactRecord value2(String value) {
        setEmailAddress(value);
        return this;
    }

    @Override
    public ContactRecord value3(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public ContactRecord value4(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public ContactRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContactRecord
     */
    public ContactRecord() {
        super(Contact.CONTACT);
    }

    /**
     * Create a detached, initialised ContactRecord
     */
    public ContactRecord(Integer id, String emailAddress, String firstName, String lastName) {
        super(Contact.CONTACT);

        setId(id);
        setEmailAddress(emailAddress);
        setFirstName(firstName);
        setLastName(lastName);
    }
}
