/*
 * This file is generated by jOOQ.
 */
package com.vancefm.ticketstack.models.tables.records;


import com.vancefm.ticketstack.models.tables.RequestCategory;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RequestCategoryRecord extends UpdatableRecordImpl<RequestCategoryRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ticketstack.request_category.id</code>.
     */
    public RequestCategoryRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ticketstack.request_category.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ticketstack.request_category.category</code>.
     */
    public RequestCategoryRecord setCategory(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ticketstack.request_category.category</code>.
     */
    @NotNull
    @Size(max = 25)
    public String getCategory() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RequestCategory.REQUEST_CATEGORY.ID;
    }

    @Override
    public Field<String> field2() {
        return RequestCategory.REQUEST_CATEGORY.CATEGORY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCategory();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCategory();
    }

    @Override
    public RequestCategoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RequestCategoryRecord value2(String value) {
        setCategory(value);
        return this;
    }

    @Override
    public RequestCategoryRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RequestCategoryRecord
     */
    public RequestCategoryRecord() {
        super(RequestCategory.REQUEST_CATEGORY);
    }

    /**
     * Create a detached, initialised RequestCategoryRecord
     */
    public RequestCategoryRecord(Integer id, String category) {
        super(RequestCategory.REQUEST_CATEGORY);

        setId(id);
        setCategory(category);
    }
}
