/*
 * This file is generated by jOOQ.
 */
package com.vancefm.ticketstack.models.tables.records;


import com.vancefm.ticketstack.models.tables.TicketStatus;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TicketStatusRecord extends UpdatableRecordImpl<TicketStatusRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ticketstack.ticket_status.id</code>.
     */
    public TicketStatusRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket_status.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ticketstack.ticket_status.status_name</code>.
     */
    public TicketStatusRecord setStatusName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket_status.status_name</code>.
     */
    @NotNull
    @Size(max = 25)
    public String getStatusName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TicketStatus.TICKET_STATUS.ID;
    }

    @Override
    public Field<String> field2() {
        return TicketStatus.TICKET_STATUS.STATUS_NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getStatusName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getStatusName();
    }

    @Override
    public TicketStatusRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TicketStatusRecord value2(String value) {
        setStatusName(value);
        return this;
    }

    @Override
    public TicketStatusRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TicketStatusRecord
     */
    public TicketStatusRecord() {
        super(TicketStatus.TICKET_STATUS);
    }

    /**
     * Create a detached, initialised TicketStatusRecord
     */
    public TicketStatusRecord(Integer id, String statusName) {
        super(TicketStatus.TICKET_STATUS);

        setId(id);
        setStatusName(statusName);
    }
}
