/*
 * This file is generated by jOOQ.
 */
package com.vancefm.ticketstack.models.tables.records;


import com.vancefm.ticketstack.models.tables.Ticket;

import java.time.LocalDateTime;

import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TicketRecord extends UpdatableRecordImpl<TicketRecord> implements Record9<Integer, String, Integer, Integer, String, Integer, LocalDateTime, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ticketstack.ticket.id</code>.
     */
    public TicketRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ticketstack.ticket.subject</code>.
     */
    public TicketRecord setSubject(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket.subject</code>.
     */
    @Size(max = 50)
    public String getSubject() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ticketstack.ticket.contact_id</code>.
     */
    public TicketRecord setContactId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket.contact_id</code>.
     */
    public Integer getContactId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>ticketstack.ticket.request_category_id</code>.
     */
    public TicketRecord setRequestCategoryId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket.request_category_id</code>.
     */
    public Integer getRequestCategoryId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>ticketstack.ticket.description</code>.
     */
    public TicketRecord setDescription(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket.description</code>.
     */
    @Size(max = 2000)
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ticketstack.ticket.status_id</code>.
     */
    public TicketRecord setStatusId(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket.status_id</code>.
     */
    public Integer getStatusId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>ticketstack.ticket.created_time</code>.
     */
    public TicketRecord setCreatedTime(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket.created_time</code>.
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>ticketstack.ticket.updated_time</code>.
     */
    public TicketRecord setUpdatedTime(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket.updated_time</code>.
     */
    public LocalDateTime getUpdatedTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>ticketstack.ticket.closed_time</code>.
     */
    public TicketRecord setClosedTime(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ticketstack.ticket.closed_time</code>.
     */
    public LocalDateTime getClosedTime() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, Integer, Integer, String, Integer, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, Integer, Integer, String, Integer, LocalDateTime, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Ticket.TICKET.ID;
    }

    @Override
    public Field<String> field2() {
        return Ticket.TICKET.SUBJECT;
    }

    @Override
    public Field<Integer> field3() {
        return Ticket.TICKET.CONTACT_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Ticket.TICKET.REQUEST_CATEGORY_ID;
    }

    @Override
    public Field<String> field5() {
        return Ticket.TICKET.DESCRIPTION;
    }

    @Override
    public Field<Integer> field6() {
        return Ticket.TICKET.STATUS_ID;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Ticket.TICKET.CREATED_TIME;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Ticket.TICKET.UPDATED_TIME;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Ticket.TICKET.CLOSED_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSubject();
    }

    @Override
    public Integer component3() {
        return getContactId();
    }

    @Override
    public Integer component4() {
        return getRequestCategoryId();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public Integer component6() {
        return getStatusId();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime component8() {
        return getUpdatedTime();
    }

    @Override
    public LocalDateTime component9() {
        return getClosedTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSubject();
    }

    @Override
    public Integer value3() {
        return getContactId();
    }

    @Override
    public Integer value4() {
        return getRequestCategoryId();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public Integer value6() {
        return getStatusId();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime value8() {
        return getUpdatedTime();
    }

    @Override
    public LocalDateTime value9() {
        return getClosedTime();
    }

    @Override
    public TicketRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TicketRecord value2(String value) {
        setSubject(value);
        return this;
    }

    @Override
    public TicketRecord value3(Integer value) {
        setContactId(value);
        return this;
    }

    @Override
    public TicketRecord value4(Integer value) {
        setRequestCategoryId(value);
        return this;
    }

    @Override
    public TicketRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public TicketRecord value6(Integer value) {
        setStatusId(value);
        return this;
    }

    @Override
    public TicketRecord value7(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public TicketRecord value8(LocalDateTime value) {
        setUpdatedTime(value);
        return this;
    }

    @Override
    public TicketRecord value9(LocalDateTime value) {
        setClosedTime(value);
        return this;
    }

    @Override
    public TicketRecord values(Integer value1, String value2, Integer value3, Integer value4, String value5, Integer value6, LocalDateTime value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TicketRecord
     */
    public TicketRecord() {
        super(Ticket.TICKET);
    }

    /**
     * Create a detached, initialised TicketRecord
     */
    public TicketRecord(Integer id, String subject, Integer contactId, Integer requestCategoryId, String description, Integer statusId, LocalDateTime createdTime, LocalDateTime updatedTime, LocalDateTime closedTime) {
        super(Ticket.TICKET);

        setId(id);
        setSubject(subject);
        setContactId(contactId);
        setRequestCategoryId(requestCategoryId);
        setDescription(description);
        setStatusId(statusId);
        setCreatedTime(createdTime);
        setUpdatedTime(updatedTime);
        setClosedTime(closedTime);
    }
}
