version: "3.8"
networks:
  ticket-stack-net:
    driver: bridge

services:
  api:
    image: ticket-stack-api:latest
    build: .
    networks:
      - ticket-stack-net
    ports:
      - "8080:8080"

  kafka-broker0:
    #Using the Bitnami Kafka image
    image: 'bitnami/kafka:latest'
    working_dir: /opt/bitnami/kafka/bin
    networks:
      - ticket-stack-net
    ports:
      - "9093:9093"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://0.0.0.0:9093,CONTROLLER://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-broker0:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - BITNAMI_DEBUG=yes

volumes:
  kafka_data:
    driver: local